
--- Data Analysis


--Q1]. Find the number of stores in each country.

select country,
	   count(distinct store_id) as total_stores
from stores
group by country



--Q2] Calculate the total number of units sold by each store.
select store_id,
	   sum(quantity) as total_quantity
from sales
group by store_id
order by total_quantity


--Q3] Determine how many stores have never received a warranty claim. 
 
select count(*)
from stores
where store_id not in (
						select distinct store_id 
						from sales as s inner join warranty as w 
						on s.sale_id = w.sale_id
)
					


-- Q4] Calculate the total units sold and revenue generated by each store.

-- For Total Quantity
select store_id ,
	   sum(quantity) as total_units 
from sales group by store_id

-- for total revenue

with revenue_table 
as
(SELECT sale_id,
		s.store_id,
		p.product_id,
		s.quantity,
		p.price,
		((s.quantity * p.price)) as total_revenue
from sales s 
join products p 
on   s.product_id = p.product_id ) 

SELECT rt.store_id ,
	   st.store_name,
	   sum(rt.total_revenue) as total_revenue
from revenue_table rt join stores st 
on rt.store_id =st.store_id
group by rt.store_id,st.store_name

 
-- Q5] Identify the store with the highest total units sold in the last year

SELECT s1.store_id,
	   s2.store_name,
	   sum(quantity) as total_unit
from sales s1  
join stores s2 
on   s1.store_id = s2.store_id
group by s1.store_id ,s2.store_name
order by total_unit desc
limit 1

-- Q6] Analyze the year-over-year growth rate for each store.

with revenue_table 
as
(SELECT 
	s.store_id,
	sum(((s.quantity * p.price))) as current_year_total_revenue,
	extract( year from sale_date) as sale_year
from sales s 
join products p 
on   s.product_id = p.product_id 
group by s.store_id,sale_year) 

SELECT rt.store_id,s2.store_name,
	   sale_year,
	   current_year_total_revenue,
	   lag(current_year_total_revenue) over( partition by rt.store_id order by sale_year) as prev_year_total_revenue,
  	   round(((((current_year_total_revenue- lag(current_year_total_revenue) over( partition by 
		 rt.store_id order by sale_year))/lag(current_year_total_revenue) over( partition by 
		 rt.store_id order by sale_year)))*100)) as YOY_GROWTH
from revenue_table rt 
join stores s2 
on rt.store_id=s2.store_id

--Q7] Calculate the monthly running total of sales for each store over the past four years.

with revenue_table 
as
(
SELECT 
	s.store_id,
	(s.quantity * p.price) as monthly_total_revenue,
	extract(month from sale_date) as months ,
	extract(year from sale_date) as years
from sales s 
join products p 
on s.product_id = p.product_id )

select s2.store_name,
	   rt.store_Id,
	   sum(rt.monthly_total_revenue), 
	   rt.months,
	   rt.years
from revenue_table rt 
join stores s2
on rt.store_id = s2.store_id
group by store_name,rt.store_id,rt.months,rt.years
order by rt.store_id,rt.years

-- Q8] Which stores consistently rank in the Top 5 by sales across multiple years?


WITH revenue_table AS (
    SELECT
        st.store_name,
        s.store_id,
        SUM(s.quantity * p.price) AS total_revenue,
        EXTRACT(YEAR FROM s.sale_date) AS sale_year
FROM sales s 
JOIN products p 
ON s.product_id = p.product_id 
JOIN stores st 
ON s.store_id = st.store_id
GROUP BY st.store_name, s.store_id, EXTRACT(YEAR FROM s.sale_date)
),

ranked_store AS (
SELECT	
	 store_name,
	 store_id,
     total_revenue,
     sale_year,
     DENSE_RANK() OVER(PARTITION BY sale_year ORDER BY total_revenue DESC) AS str_rnk
FROM revenue_table
)
SELECT 
    store_id,
    store_name,
    COUNT(DISTINCT sale_year) AS total_years_tracked,
    SUM(CASE WHEN str_rnk <= 5 THEN 1 ELSE 0 END) AS times_in_top_5,
    MIN(str_rnk) AS best_rank_ever,
    MAX(str_rnk) AS worst_rank_ever
FROM ranked_store
GROUP BY store_id, store_name 
ORDER BY times_in_top_5 DESC, total_years_tracked DESC;



--Q9] Which product categories show the highest year-over-year sales growth? 

WITH revenue_table AS
(
select  c.category_id,
	    c.category_name,
		sum((S.quantity * p.price)) as revenue,
		EXTRACT(year from s.sale_date) as years
       	
from category c 
join products p 
on c.category_id = p.category_id 
join sales s 
on p.product_id = s.product_id 
group by c.category_id,c.category_name,years

)

select category_id,
	   category_name,
	   years,
	   revenue,
	   lag(revenue)	over( partition by category_id ORDER by years) as prev_rev,
	   Round((((revenue- lag(revenue) over( partition by category_id 
	   ORDER by years))/ lag(revenue) over( partition by category_id 
	   ORDER by years))*100)) as YOY_GROWTH
from revenue_table


--Q10] Identify the least-selling product in each country for every year

with product_detail as 
(
SELECT s.product_id,
 	   sum(quantity) as quantitys,
	   extract(year from s.sale_date) as years,
	   st.country	
from sales s
join stores st
on s.store_id = st.store_id
group by s.product_id,years,st.country
),

rank_table as
(
select *,
	   dense_rank() over(partition by country,years 
	   order by quantitys) as rnk	
from product_detail)

SELECT r.product_id,
	   p.product_name,
	   r.quantitys,
	   r.years,
	   r.country,
	   r.rnk
from rank_table r
join products p
on r.product_id = p.product_id
where rnk = 1 



/*Q11 Analyze product sales trends by lifecycle stage:
0–6 months
6–12 months
12–18 months
18+ months*/

select	p.product_name,
		p.product_id, 
		sum(s.quantity) as units_sold,
		CASE	
			when s.sale_date < p.launch_date + interval '6 months' 
				then 'First 6 months'
			
			when s.sale_date >= p.launch_date + interval '6 months'
				 and S.sale_Date < p.launch_date + interval '12 months' 
				 	then 'Between 6 - 12 months'
			
			when s.sale_date >= p.launch_date + interval '12 months' 
				 and S.sale_Date < p.launch_date + interval '18 months' 
				 	then 'Between 12 - 18 months'
			
			when s.sale_date >= p.launch_date +interval '18 months' 
					then ' post 18 months'	 
		else 'non_valid'	
		end as life_cycle
from sales s
join products p
on s.product_id = p.product_id
group by p.product_name,p.product_id,life_cycle
order by product_name

---Q12] Which products experience the largest decline in sales after 12 months from launch?


--- 493143 tuples EXISTS in Dataset where sale date preceds launch date I.E. sale was done brfore launch of product  
--- using belown table as CTE we can count number of rows where sale_date < launch_date 

with sales_time as
(select p.product_name,
		p.product_id,
		s.quantity,
		p.launch_date,
		s.sale_date,
		case
			when s.sale_date <p.launch_date 
				THEN 'Data error : sold before launch'
			
			when s.sale_date BETWEEN p.launch_date and p.launch_date + INTERVAL '12 months' 
				THEN 'within 1 year'
			
			when s.sale_date >  p.launch_date + INTERVAL '12 months' 
				THEN 'post 1 year' 	

			else 'unknown exception'
			END as time_range
from sales s
join products p
on s.product_id = p.product_id),

sales_record as
(select  product_name,
		product_id,
		sum( case 
				when time_range = 'within 1 year' 
					THEN quantity else 0 end) as first_year,
		sum( CASE 
				WHEN time_range = 'post 1 year'	 
					THEN quantity else 0 end) as post_1_year 		

from sales_time 
group by product_name,product_id)

SELECT 	*, 
		(first_year - post_1_year) as sales_decline
from sales_record
order by sales_decline desc
          

--Q13] Calculate the percentage chance of receiving a warranty claim after purchase for each country
select  * ,
		(total_claim :: "numeric"/total_sales :: "numeric") *100 as claim_precent
FROM
	(select st.country,
			sum(s.quantity) as total_sales,
			count(w.claim_id) as total_claim
	from sales s 
	join stores st
	on s.store_id = st.store_id
	left join warranty w
	on w.sale_id = s.sale_id
	group by country)

--Q14] Determine how many warranty claims were filed within 180 days of sale.

/* select count(w.claim_id)
from warranty w
join sales s
on w.sale_id = s.sale_id
where w.claim_date < s.sale_date

This query reveals that there are 2,687 logical anomalies where the claim_date preceded the sale_date*/


/*SELECT count(
case when w.claim_date BETWEEN s.sale_date and s.sale_date + interval '180 days' THEN w.claim_id end
) as warranty_claims 
from warranty w
join sales s
on w.sale_id = s.sale_id

This query exclude 17 records which were made on same day of purchase 
*/

SELECT count(w.claim_id)
from warranty w
join sales s
on w.sale_id = s.sale_id
WHERE w.claim_date >= s.sale_date
and w.claim_date <= s.sale_date + interval '180 days' 


/*Q15] What percentage of warranty claims occur within:
0–30 days
31–90 days
91–180 days
180+ days*/

with claim_table
as (
select s.sale_date,
	   s.sale_id,
	   w.claim_id,
	   w.claim_date,
	   CASE
	   		when w.claim_date <s.sale_date then 'data error claim before sale'
	   		
			when w.claim_date >=s.sale_date and  w.claim_date <= s.sale_date + interval '30 days' 
				then 'BEFORE FIRST MONTH'
			
			when w.claim_date > s.sale_date + interval '30 days' and w.claim_date<= s.sale_date + interval '90 days' 
				then 'BETWEEN FIRST AND THIRD MONTH'       
		    
			when w.claim_date > s.sale_date + interval '90 days' and w.claim_date <= s.sale_date + interval '180 days' 
				then  'BETWEEN THIRD AND SIXTH MONTH'                                      
			
			when w.claim_date > s.sale_date + interval '180 days' 
				then 'AFTER SIXTH MONTHS'
			
			else 'UNKNOWN EXCEPTION'
			end as CLAIM_OCCURANCE
from warranty w
join sales s
on w.sale_id = s.sale_id
)
select claim_occurance,
	   count(claim_occurance) as claims,
	   ((count(claim_occurance) :: "numeric" )/((select count(claim_id) from claim_table) :: "numeric")) * 100 as claim_percent
from claim_table
group by claim_occurance
order by claim_percent desc

                                       

-- Q16] What is the average time between purchase and warranty claim for each product category? ✅ (My question)

select c.category_id,
	   c.category_name,
	   avg(claim_date - sale_date) as avg_time,
	   justify_interval(avg(claim_date - sale_date) * interval'1 day') as avg_time_months
from sales s  
join  warranty w
on s.sale_id = w.sale_id
join products p
on p.product_id = s.product_id
join category c
on p.category_id = c.category_id
where claim_date >= sale_date
group by c.category_id,c.category_name


--Q17] Which products generate the highest revenue but also have the highest warranty claim rates? 

with claim_revenue
as
(select product_name,
		p.product_id,
	    sum(price * quantity) as revenue,
	    sum (s.quantity) as total_units, 
	    count(claim_id) as claims
from sales s  
left join  warranty w
on s.sale_id = w.sale_id
join products p
on p.product_id = s.product_id
group by p.product_name,p.product_id
order by total_units desc),

kpi_metrics AS
(
select *,
		(claims ::"numeric")/(total_units::"numeric")*100 as claim_percent
FROM claim_revenue
)

select product_name,
	   product_id,
	   revenue,
	   dense_rank() over(order by revenue desc) as revenue_rank,
	   total_units,
	   claims,
	   claim_percent,
	   dense_rank() over(order by claim_percent desc) as claim_percent_rank
from kpi_metrics
order by revenue desc ,claim_percent desc





